export const featureRegistry = {
  pages: [
    { id: "library", label: "Vault Library", status: "active" },
    { id: "workspace", label: "Workspace", status: "active" },
    { id: "market", label: "Developer Market", status: "active" },
  ],
  overlays: [
    { id: "switcher", label: "Quick Switch", status: "active" },
    { id: "profile", label: "Profile", status: "active" },
    { id: "friends", label: "Friends", status: "active" },
    { id: "messages", label: "Messages", status: "active" },
    { id: "notifications", label: "Notifications", status: "active" },
    { id: "share", label: "Share Vault", status: "active" },
    { id: "settings", label: "Settings", status: "active" },
  ],
  workspaces: [
    { id: "text", label: "Note Editor", status: "legacy-bridged" },
    { id: "canvas", label: "Canvas Workspace", status: "legacy-bridged" },
    { id: "sheet", label: "Balancing Sheet", status: "legacy-bridged" },
    { id: "board", label: "Manager Board", status: "legacy-bridged" },
    { id: "graph", label: "Graph View", status: "legacy-bridged" },
  ],
  systems: [
    { id: "vaults", label: "Vaults and files", status: "active" },
    { id: "categories", label: "Library categories", status: "active" },
    { id: "import-export", label: "Workspace import/export", status: "active" },
    { id: "editor", label: "Formatting toolbar and templates", status: "legacy-bridged" },
    { id: "floating-images", label: "Floating note images", status: "legacy-bridged" },
    { id: "canvas-tools", label: "Canvas drawing and view state", status: "legacy-bridged" },
    { id: "sheet-formulas", label: "Sheet formulas and analysis", status: "legacy-bridged" },
    { id: "board-cards", label: "Board columns and cards", status: "legacy-bridged" },
    { id: "profiles", label: "Developer profile customization", status: "legacy-bridged" },
    { id: "friends", label: "Friend network", status: "legacy-bridged" },
    { id: "messages", label: "Direct and team messages", status: "legacy-bridged" },
    { id: "notifications", label: "Notification center", status: "legacy-bridged" },
    { id: "market", label: "Developer discovery", status: "partially-extracted" },
    { id: "settings", label: "Theme and software settings", status: "legacy-bridged" },
  ],
};
