import { APP_NAME, APP_VIEWS } from "../utils/constants.js";
import { randomUserId, uid } from "../utils/helpers.js";

export { uid, randomUserId };

export function createVault(name = "New Vault") {
  return {
    id: uid(),
    type: "folder",
    folderKind: "vault",
    parentId: null,
    name,
    categoryId: null,
    coverImage: "",
    owner: "You",
    members: [],
  };
}

export function createLibraryCategory(name = "New Category") {
  return {
    id: uid(),
    name,
  };
}

export function createFolder(name, parentId) {
  return {
    id: uid(),
    type: "folder",
    folderKind: "folder",
    parentId,
    name,
  };
}

export function createBoardColumn(name = "New Column", cards = []) {
  return {
    id: uid(),
    name,
    cards,
  };
}

export function createBoardCard(title = "New Card", body = "", options = {}) {
  return {
    id: uid(),
    title,
    body,
    status: options.status || "",
    priority: options.priority || "medium",
    labels: Array.isArray(options.labels) ? options.labels : [],
    sprint: options.sprint || "",
    milestone: options.milestone || "",
    watchers: Array.isArray(options.watchers) ? options.watchers : [],
    dependencies: Array.isArray(options.dependencies) ? options.dependencies : [],
    activity: Array.isArray(options.activity) ? options.activity : [],
    assignee: options.assignee || "",
    subAssignee: options.subAssignee || "",
    dueDate: options.dueDate || "",
    checklist: Array.isArray(options.checklist) ? options.checklist : [],
    comments: Array.isArray(options.comments) ? options.comments : [],
    attachments: Array.isArray(options.attachments) ? options.attachments : [],
    color: options.color || "",
  };
}

export function createSheetTable(name = "Table 1") {
  return {
    id: uid(),
    name,
    preset: "custom",
    span: 1,
    columns: ["Column 1", "Column 2", "Column 3"],
    rows: [["", "", ""], ["", "", ""], ["", "", ""]],
  };
}

export function createDoc(name, docType, parentId) {
  return {
    id: uid(),
    type: "document",
    parentId,
    name,
    docType,
    updatedAt: Date.now(),
    lastOpenedAt: Date.now(),
    content: "<p></p>",
    floatingImages: [],
    canvas: {
      strokes: [],
      nodes: [],
      edges: [],
      activeNodeId: null,
      view: { x: 0, y: 0, scale: 1 },
      filters: { query: "", type: "all", showLocked: true },
      presentationMode: false,
      snapToGrid: true,
      gridVisible: true,
    },
    sheet: {
      tables: [createSheetTable("Table 1")],
      activeTableId: null,
      selection: null,
      viewMode: "workspace",
      frozenRows: 0,
      frozenColumns: 0,
      comparisonTableId: null,
      snapshots: [],
    },
    board: {
      columns: [
        createBoardColumn("Ideas"),
        createBoardColumn("In Progress"),
        createBoardColumn("Done"),
      ],
      size: 2,
      view: "kanban",
      search: "",
      groupBy: "status",
      savedViews: [],
      archivedCards: [],
      selectedCardId: null,
      selectedColumnId: null,
    },
    storage: {
      viewMode: "grid",
      density: "comfortable",
      activeFolderId: null,
      selectedIds: [],
      search: "",
      sort: "recent",
      activeFilter: "all",
      showArchived: false,
      detailOpen: true,
      pinnedFolderIds: [],
      savedViews: [],
    },
  };
}

export function createDefaultSettings() {
  return {
    theme: "dark",
    glowMode: "cinematic",
    writingWidth: 2,
    chatSidebarWidth: 300,
    chatMembersWidth: 260,
    appearance: {
      themeVariant: "obsidian-glass",
      accentColor: "#8b5cf6",
      accentGradientFrom: "#8b5cf6",
      accentGradientTo: "#38bdf8",
      panelTransparency: 0.84,
      glassBlurStrength: 18,
      borderGlowStrength: 0.42,
      shadowIntensity: 0.34,
      cornerRoundness: 18,
      uiScale: 1,
      fontScale: 1,
      iconSize: 1,
      layoutDensity: "comfortable",
      animationIntensity: 0.7,
      reducedMotion: false,
      highContrastMode: false,
      colorblindMode: "off",
    },
    workspace: {
      sidebarWidth: 280,
      sidebarCollapsedByDefault: false,
      rememberSidebarState: true,
      rightPanelDefaultOpen: true,
      topbarDensity: "comfortable",
      showIconLabels: false,
      tabNavigation: true,
      restorePreviousTabs: true,
      pinnedPages: ["library", "market"],
      recentFilesCount: 8,
      defaultLandingPage: "library",
      vaultDashboardLayout: "grid",
      explorerSorting: "manual",
      explorerIconStyle: "glyph",
      openItemsBehavior: "tab",
      savedLayouts: [
        { id: "writer", name: "Writer Layout" },
        { id: "balancer", name: "Balancer Layout" },
        { id: "manager", name: "Manager Layout" },
        { id: "minimal", name: "Minimal Layout" },
      ],
      activeLayout: "writer",
      savedWorkspaceLayouts: [],
      activeViewMode: "comfortable",
    },
    editor: {
      defaultEditorWidth: 2,
      textSize: 1,
      lineHeight: 1.65,
      paragraphSpacing: 1,
      stickyToolbar: true,
      floatingSelectionToolbar: false,
      showWordCount: true,
      showReadingTime: true,
      showBlockCount: true,
      autoSaveInterval: 800,
      autoRecovery: true,
      markdownShortcuts: true,
      slashCommands: true,
      focusMode: false,
      distractionFreeMode: false,
      typewriterMode: false,
      showOutlinePanel: true,
      showBreadcrumbs: true,
      showDocumentMinimap: false,
      presets: [
        { id: "writer", name: "Writer" },
        { id: "review", name: "Review" },
        { id: "focus", name: "Focus" },
      ],
      sectionPresetMode: "guided",
    },
    sheets: {
      tableDensity: "comfortable",
      stickyHeaders: true,
      formulaBarAlwaysVisible: true,
      formulaSuggestions: true,
      highlightReferencedColumns: true,
      showRowNumbers: true,
      showColumnLabels: true,
      zebraRows: true,
      decimalPrecision: 2,
      autoFormatNumbers: true,
      keyboardNavigation: true,
      enterBehavior: "move-down",
      tabBehavior: "move-right",
      duplicateRowShortcut: "Ctrl+D",
      activeProfile: "economy",
      profiles: [
        { id: "economy", name: "Economy Balancing" },
        { id: "combat", name: "Combat Balancing" },
        { id: "loot", name: "Loot Balancing" },
        { id: "progression", name: "Progression Balancing" },
      ],
    },
    boards: {
      cardDensity: "comfortable",
      columnWidth: 380,
      metadataVisibility: "full",
      dueDateVisibility: true,
      ownerVisibility: true,
      checklistPreview: true,
      defaultBoardPreset: "production",
      quickAddCardOnEnter: true,
      archiveCompletedItems: false,
      workloadCounters: true,
      highlightOverdueTasks: true,
      defaultBoardSize: 2,
    },
    canvas: {
      gridVisibility: true,
      gridSize: 24,
      snapStrength: 0.6,
      connectorStyle: "curve",
      defaultNodeColor: "#8b5cf6",
      zoomSensitivity: 1,
      panSensitivity: 1,
      miniMapToggle: false,
      autoAlignGuides: true,
      smartSnapping: true,
      drawingSmoothing: 0.75,
    },
    fileVault: {
      defaultSmartView: "recent",
      allowMultiUpload: true,
      preserveVersions: true,
      showPreviewPanel: true,
      defaultSort: "recent",
      defaultViewMode: "grid",
      defaultDensity: "comfortable",
      showHiddenMetadata: false,
    },
    notifications: {
      teamNotifications: "in-app",
      marketplaceNotifications: "badge",
      systemNotifications: "in-app",
      emailNotifications: false,
      muteMarketplaceSuggestions: false,
      mutedTeamIds: [],
      mutedProjectIds: [],
      autoExpireDays: 30,
      directMessages: "in-app",
      friendRequests: "badge",
      mentions: "in-app",
      sharedVaultUpdates: "in-app",
      boardAssignments: "in-app",
      dueDateReminders: "badge",
      collaborationInvites: "in-app",
      marketplaceActivity: "badge",
      systemAnnouncements: "in-app",
      quietHoursStart: "23:00",
      quietHoursEnd: "08:00",
      doNotDisturb: false,
      priorityNotifications: true,
    },
    friendsMessages: {
      whoCanMessageYou: "friends-and-collaborators",
      whoCanSendFriendRequests: "everyone",
      onlineStatusVisibility: "friends",
      activityVisibility: "friends",
      typingIndicators: true,
      readReceipts: true,
      messagePreviewInNotifications: true,
      compactChatMode: false,
    },
    marketplace: {
      availabilityStatus: "open-to-offers",
      visibleRoleTags: ["Game Designer", "Producer", "Balancing Specialist"],
      featuredSkills: ["Systems Design", "Economy Tuning", "Production Planning"],
      rateVisibility: "public",
      collaborationPreferences: "remote-collab",
      projectTypePreferences: ["roblox", "indie", "live-ops"],
      compensationPreference: "paid",
      showProfilePreview: true,
    },
    profile: {
      profileUrl: "",
      visibleBadges: true,
      headline: "Design discipline beats chaos.",
      availabilityStatus: "available",
      portfolioBlockOrder: ["About", "Skills", "Projects", "Achievements"],
      pinnedProject: "",
      customProfileAccent: "#8b5cf6",
      publicFields: ["headline", "role", "bio", "skills", "portfolio"],
    },
    accessibility: {
      highContrastMode: false,
      largerClickTargets: false,
      reducedMotion: false,
      keyboardNavigationMode: false,
      focusRingIntensity: 0.75,
      textScaling: 1,
      dyslexiaFriendlyFont: false,
      colorblindSupport: "off",
    },
    shortcuts: {
      newFile: "Ctrl+N",
      openFile: "Ctrl+P",
      commandPalette: "Ctrl+K",
      insertBlock: "Ctrl+/",
      quickActions: ["New Note", "New Sheet", "Create Board"],
      topbarActions: ["Search", "Messages", "Notifications", "Settings"],
      toolbarButtons: ["Bold", "Italic", "Heading", "List", "Code"],
    },
    advanced: {
      performanceMode: false,
      disableAnimations: false,
      developerMode: false,
      experimentalFeatures: false,
    },
  };
}

export function createDefaultSettingsMeta() {
  return {
    favorites: [],
    recent: [],
    presets: [
      { id: "studio-core", name: "Studio Core", settings: createDefaultSettings() },
      {
        id: "writer-focus",
        name: "Writer Focus",
        settings: {
          ...createDefaultSettings(),
          writingWidth: 1,
          editor: {
            ...createDefaultSettings().editor,
            focusMode: true,
            distractionFreeMode: true,
            defaultEditorWidth: 1,
          },
          workspace: {
            ...createDefaultSettings().workspace,
            activeLayout: "writer",
          },
        },
      },
    ],
    activeCategory: "appearance",
    search: "",
    draftPresetName: "",
  };
}

export function createDefaultStateSnapshot() {
  return {
    activeView: APP_VIEWS.LIBRARY,
    selectedVaultId: null,
    selectedNodeId: null,
    activeDocumentId: null,
    sidebarCollapsed: false,
    contextPanelCollapsed: false,
    comparisonDocumentId: null,
    collapsedFolders: [],
    softwareName: APP_NAME,
    profile: {
      name: "You",
      userId: randomUserId(),
      accountId: "",
      publicId: "",
      bio: "Game designer building worlds, systems, and production pipelines.",
      tagline: "Design discipline beats chaos.",
      role: "Creative Director",
      status: "Available for collaboration",
      location: "Studio Workspace",
      avatar: "",
      banner: "",
      accent: "#8b5cf6",
      themeVariant: "dark-glass",
      layoutStyle: "studio",
      badges: ["Game Designer"],
      blocks: ["About", "Skills", "Projects", "Achievements"],
      note: "",
      friends: [],
      friendRequests: [],
      sentRequests: [],
      blockedUsers: [],
    },
    social: {
      conversations: [],
      activeConversationId: null,
      directory: [],
      categories: [
        { id: "general", name: "General" },
        { id: "team", name: "Team" },
      ],
      activeSection: "direct",
      activeChannelId: null,
      searchQuery: "",
      typing: {},
      savedMessages: [],
      unreadByConversation: {},
      notificationPrefs: {},
      communities: [],
      workspaces: [],
    },
    marketProfiles: [],
    notifications: [],
    starredItems: [],
    pinnedItems: [],
    fileVault: {
      files: [],
      smartViews: ["recent", "favorites", "shared", "archived", "images", "documents"],
      activeView: "recent",
      search: "",
      selectedFileId: null,
      folders: [],
      tags: [],
      categories: [],
      links: [],
      permissions: [],
      versions: [],
      activity: [],
      views: [],
      trash: [],
      activeFolderId: null,
      sort: "recent",
      viewMode: "grid",
      density: "comfortable",
      selectedIds: [],
    },
    settings: createDefaultSettings(),
    settingsMeta: createDefaultSettingsMeta(),
    libraryCategories: [],
    openTabs: [],
    items: [],
  };
}

export function createBaseStateSnapshot() {
  return createDefaultStateSnapshot();
}
